---
apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::9876543210:role/argo-crane-push
    kubernetes.io/enforce-mountable-secrets: "true"
  name: argo-crane-push
  namespace: argo
secrets: []
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: argo-crane-push
  namespace: argo
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: argo-update-workflow
subjects:
  - kind: ServiceAccount
    name: argo-crane-push
    namespace: argo
