apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: argo-update-workflow
  namespace: argo
rules:
  - apiGroups:
      - argoproj.io
    resources:
      - workflows
      - workflowtaskresults
    verbs:
      - get
  - apiGroups:
      - ""
    resources:
      - pods
    verbs:
      - patch
---
apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::0123456789:role/argo-docker-build
    kubernetes.io/enforce-mountable-secrets: "true"
  name: argo-docker-build
  namespace: argo
secrets:
  - name: build-notification
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: argo-docker-build
  namespace: argo
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: argo-update-workflow
subjects:
  - kind: ServiceAccount
    name: argo-docker-build
    namespace: argo
